### ISSUE TITLE
[Bug] Discord Exceptions Fail when > 2000 Characters

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#117]
Traces with more than 2000 characters are rejected by discord. 
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/notifications.py", line 23, in emit
    self.webhook.send(f'```{fmt}```' if "\n" in fmt else fmt)
  File "/home/netkan/.local/lib/python3.7/site-packages/discord/webhook.py", line 744, in send
    return self._adapter.execute_webhook(wait=wait, file=file, files=files, payload=payload)
  File "/home/netkan/.local/lib/python3.7/site-packages/discord/webhook.py", line 147, in execute_webhook
    maybe_coro = self.request('POST', url, multipart=multipart, payload=data, files=files_to_pass)
  File "/home/netkan/.local/lib/python3.7/site-packages/discord/webhook.py", line 310, in request
    raise HTTPException(r, response)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
```
In general we probably want the last part of the stack trace, so truncating at 2000 is likely going to cut off a lot useful information.

**Comment by HebaruSan** [comment]
It would be nice to have the first 1000 bytes plus the last 1000 bytes, presumably with "..." in between

**Comment by techman83** [comment]
Yeah, that'd probably be enough to get the details we need from a stack trace.

**Comment by HebaruSan** [comment]
Or, we could send multiple 2000-char messages in a row and not lose any info. This is probably rare enough that it wouldn't be too spammy.
