### ISSUE TITLE
[Bug] Worker start times out during git clone

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#123]
Clones are taking longer than 30 seconds on service start, leading to the worker being terminated.
```
[2020-01-24 05:49:55 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-01-24 05:49:55 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-01-24 05:49:55 +0000] [1] [INFO] Using worker: sync
[2020-01-24 05:49:55 +0000] [8] [INFO] Booting worker with pid: 8
# github.com:22 SSH-2.0-babeld-1f0633a6
[2020-01-24 05:50:25 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2020-01-24 05:50:25 +0000] [8] [INFO] Worker exiting (pid: 8)
[2020-01-24 05:50:25 +0000] [31] [INFO] Booting worker with pid: 31
```
Leading to exceptions
```
Uncaught exception:
Traceback (most recent call last):
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/webhooks/inflate.py", line 21, in inflate_hook
    pull_all(current_app.config['repos'])
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/common.py", line 21, in pull_all
    r.remotes.origin.pull('master', strategy_option='theirs')
  File "/home/netkan/.local/lib/python3.7/site-packages/git/remote.py", line 811, in pull
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/remote.py", line 676, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/cmd.py", line 417, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull --strategy-option=theirs -v origin master
  stderr: 'error: Your local changes to the following files would be overwritten by merge:
    download_counts.json
Please commit your changes or stash them before you merge.
Aborting'
```
Checking the repo, it was in quite a weird state.
```
On branch master
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    deleted:    10kmOmniEVA4RT/10kmOmniEVA4RT-1-1.ckan
    deleted:    10kmOmniEVA4RT/10kmOmniEVA4RT-1.0.ckan
    deleted:    10kmOmniEVA4RT/10kmOmniEVA4RT-1.ckan
    deleted:    2KASJ0523Planetarysystem/2KASJ0523Planetarysystem-0.1.1.ckan
    deleted:    4kSP/4kSP-0.1.ckan
    deleted:    4kSP/4kSP-0.1b.ckan
    deleted:    64k-overhaul/64k-overhaul-v1.2.ckan
    deleted:    64xscale128xdistance/64xscale128xdistance-mk2.ckan
    deleted:    A6Intruder/A6Intruder-104.105.ckan
    deleted:    A6Intruder/A6Intruder-3.kerbalstuff
    deleted:    A7Corsair2/A7Corsair2-2.0.ckan
    deleted:    A7Corsair2/A7Corsair2-2.ckan
    deleted:    A7Corsair2/A7Corsair2-3.0.ckan
<snip>
  (use "git add <file>..." to include in what will be committed)

    10kmOmniEVA4RT/
    2KASJ0523Planetarysystem/
    4kSP/
    64k-overhaul/
    64xscale128xdistance/
    A6Intruder/
    A7Corsair2/
    AAResourceTanks/
    AATI-Flags/
    ABCORS/
    ABLaunchers/
    ADIOS/
    AECS-Motion-Suppressor/
    AGExt/
    AGroupOnStage/
    AIES-DeimosRast/
    AIES-Patches/
    AIES-TK421d/
    AIESAerospace-Unofficial/
    AJEExtendedConfigs/
    ALCOR/
    ALCORIVAPatch/
    AMEG/
    APModpack/
    ASET-PRC/
    ASETAgency/
    ASETAvionics/
    ASETProps-CE/
    ASETProps/
    ASupremePartsMod/
    AT-Utils/
    ATKPropulsionPack/
    AUCAeronautictechnology/
    AV8HarrierWITHTRUEVTOLFlight/
    AVP-2kTextures/
    AVP-4kTextures/
    AVP-8kTextures/
    AVeryKerbalChristmas/
    AblativeAirbrake/
    AbovetheSkySoyuzTMAandR7/
    Achievements/
    ActionGroupManager/
```

**Comment by HebaruSan** [comment]
Maybe we could increase the timeout if we wanted to:

https://docs.gunicorn.org/en/stable/settings.html#timeout

**Comment by HebaruSan** [comment]
Or, I was just looking at `--preload` today. Maybe this would allow the setup to complete before the workers are spawned.

https://docs.gunicorn.org/en/stable/settings.html#preload-app

**Comment by techman83** [comment]
Considering how we deploy the application (via docker), this is likely a sensible option to use. I'll pop a PR through as a formalisation, but I updated the stack with the flag and it seems to do what it says on the tin. If we need multiple workers at some point we'll want to think about that, but I don't think we're even remotely close to needing it right now.

```
docker logs -f 764473186f02
# github.com:22 SSH-2.0-babeld-1f0633a6
[2020-01-27 02:47:58 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-01-27 02:47:58 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-01-27 02:47:58 +0000] [1] [INFO] Using worker: sync
[2020-01-27 02:47:58 +0000] [30] [INFO] Booting worker with pid: 30
```

**Comment by HebaruSan** [comment]
Another nice thing about the current Infra is that the workload for handling each webhook call is so low, basically just creating a queue entry, that we could probably handle a lot more traffic with a single worker.

**Comment by techman83** [comment]
Yeah, the decoupling of things has been a really big success to how its all running. We'd run into git interaction issues before we'd even be able to scale the worker. Problem well well into the future I think :slightly_smiling_face:
