### ISSUE TITLE
[Bug] Upload causes mirrorer to crash

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#133]
Problem
-------
Upload succeeds, but crashes the process when returning.
```
[2020-01-30 01:11:13,750] [ERROR   ] Uncaught exception:
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/bin/netkan", line 8, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli.py", line 366, in mirrorer
    ).process_queue(queue, timeout)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/mirrorer.py", line 52, in process_queue
    if self.try_mirror(CkanMirror(path)):
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/mirrorer.py", line 80, in try_mirror
    return self.try_upload(ckan, tmp.file)
  File "/usr/local/lib/python3.7/tempfile.py", line 499, in __exit__
    result = self.file.__exit__(exc, value, tb)
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/bin/netkan", line 8, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli.py", line 366, in mirrorer
    ).process_queue(queue, timeout)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/mirrorer.py", line 52, in process_queue
    if self.try_mirror(CkanMirror(path)):
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/mirrorer.py", line 80, in try_mirror
    return self.try_upload(ckan, tmp.file)
  File "/usr/local/lib/python3.7/tempfile.py", line 499, in __exit__
    result = self.file.__exit__(exc, value, tb)
OSError: [Errno 9] Bad file descriptor

```

I suspect the problem lies within the context manager:
```python
        cached_file = self.cache_find_file(ckan)
        if cached_file:
            # If the download is in the cache, use it
            with cached_file.open(mode='rb') as file:
                logging.info('Found matching cache entry at %s', cached_file)
                return self.try_upload(ckan, file)
        else:
            # Download the file as needed
            with tempfile.NamedTemporaryFile() as tmp:
                logging.info('Downloading %s', ckan.download)
                urllib.request.urlretrieve(ckan.download, tmp.name)
                logging.info('Downloaded %s to %s', ckan.mirror_item(), tmp.name)
                return self.try_upload(ckan, tmp.file)
```
We're returning within the context manager, I suspect it's trying to close it after we've left the scope.

**Comment by HebaruSan** [comment]
Hmm, why would that be a problem, though? It's an object, we're done with it, it's being disposed. How would that corrupt the file descriptor?

Another possibility is slight misuse of the `NamedTemporaryFile`. Python creates the temp file and returns it to us, and then we use the name to overwrite it with a download, and then we use the original file handle for uploading after that. It seems to be working, but I could imagine Python being confused by that sequence of operations in ways that reveal themselves upon exiting the scope.

https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile

> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

**Comment by techman83** [comment]
Actually, yes, if retrieve is writing to that like a file handle; probably not ideal. I only had time to create the issue, anything else would have led to a PR :wink:

**Comment by HebaruSan** [comment]
This seems to be resolved now, uploads have been proceeding without errors. Probably in #136.
