### ISSUE TITLE
[Bug] Volume burst credits randomly dropping massively

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/NetKAN-Infra#216]
Problem
-------
Every now and then, something in our infrastructure causes a sustained read from the mounted SSD storage, burning through the volume burst credits in a matter of minutes.
It happens without heads-up and instantly.
Every time this happens, our scheduler stops scheduling new netkans for inflation in an attempt to allow the credits to recover again.

Only a restart of the instance seems to fix it.

Recently it happened twice within 7 days.

A graph showing the volume credits during both recent occasions:
![graph credits](https://cdn.discordapp.com/attachments/601455398553387008/823358933241561108/unknown.png)

A graph showing the read bandwith during the last occasion
![graph read badnwidth](https://cdn.discordapp.com/attachments/601455398553387008/823563001188974662/unknown.png)

It is yet unknown what causes this, however @techman83 suspects something in the git repositories getting dirty after time, which somehow makes git get stuck during some operations.

Please use this issue to gather guesses and possible investigation results.

**Comment by HebaruSan** [comment]
It would be nice to know:

- Which container does the bad thing? Fixing the Inflator would look very different from fixing the Indexer could look very different from fixing the Mirrorer, etc.
  - Can we restart them individually?
- Which files are being accessed (if I'm interpreting correctly that files are being accessed)?

**Comment by HebaruSan** [comment]
2021-03-21 9:30 AM UTC doesn't seem to correlate to any particular activity in CKAN-meta. TestFlight-2.0.0 was indexed just after midnight, and then download counter ran after noon.

So in theory we can rule out anything associated with a new mod being downloaded, indexed, etc.

**Comment by techman83** [comment]
> It would be nice to know:
> 
> * Which container does the bad thing? Fixing the Inflator would look very different from fixing the Indexer could look very different from fixing the Mirrorer, etc.

Historically it's been the indexer. This was happening very frequently before #178 and only recently has it returned as a more frequent issue.
   
>  * Can we restart them individually?

We could, I definitely can. I would like to run some manual gc on the git repos, see if it changes anything.

> * Which files are being accessed (if I'm interpreting correctly that files are being accessed)? It might be something in `.git`, but it could also be something with the cached mod files, etc.

Cached mods live on separate disk. So that shouldn't be an issue. Most of the services do file operations, but under normal conditions they don't consume enough to make an impact. Something happens after a time and suddenly we're using a lot of IO. Considering how we use git, and how it operates under the hood, to me sounds like the most likely cause.

Unfortunately my quick search has only revealed older info and I know the garbage collection stuff has been improved significantly over the last couple of years. Now we may have to add some checks to force something or we may be able to get away with setting some config flags so that the regular gc that runs during pulls/commits/pushes/branches etc cleans more aggressively.

**Comment by HebaruSan** [comment]
> Historically it's been the indexer. This was happening very frequently before #178 and only recently has it returned as a more frequent issue.

Which container is the culprit _recently_? Is there a way to tell?

**Comment by techman83** [comment]
Not easily I don't think. Not without running something like iotop when we're experiencing the issue.

**Comment by HebaruSan** [comment]
> Not easily I don't think. Not without running something like iotop when we're experiencing the issue.

> > * Can we restart them individually?
> 
> We could, I definitely can. I would like to run some manual gc on the git repos, see if it changes anything.

OK, in that case, let's plan to try that carefully next time this problem happens. Whichever container we think is the most likely cause, restart that one first and wait to see whether it's fixed. If not, then try the next most likely, and so on. Once we know who is doing all these reads and using up all the credits, we can focus on looking for problems with that specific code and environment.

Based on discussions so far, I would suggest this ordering initially, alterations welcome:

1. Indexer
2. Webhooks
3. Inflator
4. Mirrorer
5. SpaceDockAdder

Also, in case we haven't been doing this, a quick check to see if any of our scheduled non-persistent tasks is running would probably be a good idea before starting to bounce services, assuming we can check that.

Does that sound like a reasonable plan?

**Comment by techman83** [comment]
Sounds like a reasonable plan of attack. I may insert a step prior, and see if any GC commands make a difference + get some reports out of the repo.

**Comment by HebaruSan** [comment]
Good observation by @techman83, we had clusters of staging PRs submitted right around when these downtimes happened:

https://github.com/KSP-CKAN/CKAN-meta/pulls?q=is%3Apr+is%3Aclosed

**Comment by HebaruSan** [comment]
We just received this in Discord. Don't know whether it's related.

```
Uncaught exception:
Traceback (most recent call last):
  File ".local/bin/netkan", line 8, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli/services.py", line 29, in indexer
    with MessageHandler(common.ckanmeta_repo, common.github_pr) as handler:
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/indexer.py", line 183, in __enter__
    self.ckm_repo.pull_remote_branch('master')
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/repos.py", line 43, in pull_remote_branch
    self.git_repo.remotes.origin.pull(branch_name, strategy_option=strategy_option)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/remote.py", line 814, in pull
    universal_newlines=True, v=True, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/cmd.py", line 1011, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/cmd.py", line 735, in execute
    **subprocess_kwargs
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

This is where that is in the indexer:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/245494cb4b3248813367e7bc82e2feb00718a68d/netkan/netkan/indexer.py#L183

**Comment by techman83** [comment]
Burst credit usage
![2021-04-06_08-15-37](https://user-images.githubusercontent.com/3467784/113641874-0e67e600-96b1-11eb-899a-60b65ee94bfa.png)

Read throughput
![2021-04-06_08-18-37](https://user-images.githubusercontent.com/3467784/113641746-d660a300-96b0-11eb-8fa6-4b8c7424a3dd.png)

Read bandwidth
![2021-04-06_08-17-55](https://user-images.githubusercontent.com/3467784/113641781-e4162880-96b0-11eb-85fa-a53c0a8f6c3f.png)

Then it recovered after the indexer exceeded its memory allocation. Which likely makes sense, as the tree gets dirtier, it has to pull a lot more bits and pieces into memory during operations.

The real question is, can we tune the auto GC that happens during porcelain operations (pull/push/commit etc) or will we need some way to trigger periodic agressive gc / repacks (we could set a flag on the daily indexing run with sqs, or a special gc message type).
