### ISSUE TITLE
[Bug] Scheduler throws on last Batch Submit

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#24]
This is a relatively benign bug, but if the last sqs submission contains no messages it throws the following:
```
[2019-09-16 00:39:20,150] [INFO    ] Scheduler started at log level 20
[2019-09-16 00:39:20,297] [INFO    ] Cloning https://github.com/KSP-CKAN/NetKAN.git
Traceback (most recent call last):
  File ".local/bin/netkan", line 10, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli.py", line 114, in scheduler
    scheduler.schedule_all_netkans()
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/scheduler.py", line 54, in schedule_all_netkans
    self.client.send_message_batch(**self.sqs_batch_attrs(batch))
  File "/home/netkan/.local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EmptyBatchRequest: An error occurred (AWS.SimpleQueueService.EmptyBatchRequest) when calling the SendMessageBatch operation: There should be at least one SendMessageBatchRequestEntry in the request.
```
I haven't noticed this before, maybe I just got lucky and always had an amount divisible by 10 :joy:

**Comment by HebaruSan** [comment]
> got lucky and always had an amount divisible by 10

I think it's the other way around&mdash;if you have a multiple of 10, then the final `yield(batch)` of `sqs_batch_entries` returns an empty list. And we have 1760 `.netkan` files as of KSP-CKAN/NetKAN#7383.
