### ISSUE TITLE
AutoFreezer fails to re-use branch and PR

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#302]
## Problem

The AutoFreezer runs once a week, pushes a branch, and creates a pull request.

If we don't merge the PR and delete the branch within a week, the next attempt fails. If this happens 3 weeks in a row, then some mods can pass through the window where they're idle enough to be considered (1000 days) but not idle enough to be skipped as permanently active (1021 days) without being reviewed. We've had a few such spans now, so we'll have to do some catch-up eventually.

### History

I started trying to grapple with this in #281; I thought the problem was we weren't pulling the branch before switching to it, but switching to `XkanRepo.change_branch` didn't help. The push fails, even though this exact scenario works fine for the Indexer and the Adder.

Then #286 started logging stack traces for failed pushes, which didn't tell us anything.

**Comment by techman83** [comment]
It's definitely still occurring, curious as to why. We do have other processes that re-use the same branch (staging) for such things.

```python
Uncaught exception:
Traceback (most recent call last):
  File ".local/bin/netkan", line 8, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli/utilities.py", line 39, in auto_freezer
    afr.freeze_idle_mods(days_limit, days_till_ignore)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/auto_freezer.py", line 29, in freeze_idle_mods
    logging.info('Already froze %s', ident)
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/repos.py", line 135, in change_branch
    f'{branch_name}:{branch_name}'
  File "/home/netkan/.local/lib/python3.7/site-packages/git/remote.py", line 297, in raise_if_error
    raise self.error
  File "/home/netkan/.local/lib/python3.7/site-packages/git/remote.py", line 927, in _get_push_info
    proc.wait(stderr=stderr_text)
  File "/home/netkan/.local/lib/python3.7/site-packages/git/cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push --porcelain -- origin freeze/auto:freeze/auto
  stderr: 'error: failed to push some refs to 'github.com:KSP-CKAN/NetKAN.git''
```

**Comment by techman83** [comment]
Hmmmmmm
```
error: failed to push some refs to 'github.com:KSP-CKAN/NetKAN.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
