### ISSUE TITLE
[Bug] Scheduler fails on 'KeyError' when no '$kref'

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#43]
We should use the dictionary get method here.
```python
Traceback (most recent call last):
  File ".local/bin/netkan", line 10, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli.py", line 118, in scheduler
    scheduler.schedule_all_netkans()
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/scheduler.py", line 80, in schedule_all_netkans
    for batch in self.sqs_batch_entries():
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/scheduler.py", line 65, in sqs_batch_entries
    if self.force_all or not netkan.hook_only():
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/scheduler.py", line 31, in hook_only
    return self.on_spacedock() and not self.has_vref()
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/scheduler.py", line 21, in on_spacedock
    kref = self.json['$kref']
KeyError: '$kref'
```

**Comment by techman83** [comment]
I'm going to look at this and a couple of other things shortly.

**Comment by HebaruSan** [comment]
Since it took a little bit of effort, the list of netkans without krefs for posterity:

```
AdaptiveDockingNode.netkan
AIESAerospace-Unofficial.netkan
APModpack.netkan
AsteroidDay.netkan
AtmosphericSoundEnhancement.netkan
AUCAeronautictechnology.netkan
BananaForScale-large.netkan
BananaForScale-small.netkan
BearLandingLegLTB.netkan
BoxSat.netkan
BoxSat-prototypes.netkan
CanadianFlags.netkan
ContractConfigurator-SCANsat.netkan
CoolRockets.netkan
CustomDesignSpacesuits-Steampunk.netkan
DDSLoader.netkan
ElectricThrustEngineETE.netkan
FwiffoRaredenSkybox.netkan
HGR.netkan
IR-Model-Rework-Core.netkan
IR-Model-Rework-Expansion.netkan
IR-Model-Rework-Utility.netkan
KerbalLaunchVehicles.netkan
KerBalloons.netkan
KerbalStats.netkan
KerbinCup.netkan
KSPRC-Textures.netkan
LightsOut-Fwiffo.netkan
Mk2Essentials.netkan
ModularFuelTanks.netkan
ModuleRCSFX.netkan
Nuke-TinyParts.netkan
PartOverhauls.netkan
ProceduralProbes.netkan
RocketdyneF-1.netkan
SciFiVisualEnhancements.netkan
SpaceDock.netkan
SpaceShuttleEngines.netkan
StationScience.netkan
```
