### ISSUE TITLE
[Bug] SpaceDock Webhook Throws an Exception

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#63]
```
ERROR:netkan.webhooks:Exception on /inflate [POST]
Traceback (most recent call last):
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/webhooks/inflate.py", line 14, in inflate_hook
    ids = request.json.get('identifiers')
AttributeError: 'NoneType' object has no attribute 'get'
172.17.0.6 - - [23/Oct/2019:11:21:44 +0000] "POST /inflate HTTP/1.0" 500 290 "-" "python-requests/2.22.0"
ERROR:netkan.webhooks:Exception on /inflate [POST]
Traceback (most recent call last):
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/netkan/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/webhooks/inflate.py", line 14, in inflate_hook
    ids = request.json.get('identifiers')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by DasSkelett** [comment]
So `request.json` is `None`? That either means the payload is no valid json, or totally empty, right?

Aside that we should catch this of course, that looks like a bug from SpaceDocks side too. Maybe if SD can't find the identifier to the mod?

**Comment by HebaruSan** [comment]
Oh shoot, I think that happens if `Content-Type: application/json` isn't passed as an HTTP header. That's why it was included in my `wget` command. I guess we have to explicitly parse the body ourselves. Thanks, Flask!!
