### ISSUE TITLE
[Bug] Bot only crawling about 30 mods at the moment

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#66]
## Problem

1. Go to http://status.ksp-ckan.space/
2. Sort by Last Checked
3. Scroll down to where the times jump from short to long; currently it's here:
  ![image](https://user-images.githubusercontent.com/1559108/67504543-309dad80-f64f-11e9-99f1-ae192ea2275e.png)

The mods with recent times only number about 30. The rest aren't being checked.
Are the remaining mods not being scheduled? Is the Inflator stopping mid-pass?

### Clues

- Started happening after #48 was merged
- The inflation webhooks are working
- Inflator hasn't been changed
- Indexer hasn't been changed
- Scheduler had a parameter and a local variable renamed, which should have had no effect, but who knows
- The most recently checked mod is pretty consistently `ContractConfigurator-KFiles`

**Comment by HebaruSan** [comment]
I think the Scheduler is throwing this while retrieving the Netkans:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "NetKAN-Infra/netkan/netkan/scheduler.py", line 26, in <genexpr>
    return (Netkan(f) for f in self.path.glob('*.netkan'))
  File "NetKAN-Infra/netkan/netkan/metadata.py", line 20, in __init__
    self.kref).groups()
  File "NetKAN-Infra/netkan/netkan/metadata.py", line 37, in __getattr__
    raise AttributeError
```

So it looks related to the change in how `kref_src` and `kref_id` are set.
