### ISSUE TITLE
[Bug] Exception on comparing 'last_error'

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#71]
Problem
-------
If there is no 'last_error' in ModStatus an exception is being thrown, we should be able to use a `.get`.

```python
Traceback (most recent call last):
  File ".local/bin/netkan", line 8, in <module>
    sys.exit(netkan())
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/netkan/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/cli.py", line 79, in indexer
    handler.process_ckans()
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/indexer.py", line 242, in process_ckans
    self.process_queue(self.master)
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/indexer.py", line 223, in process_queue
    ckan.process_ckan()
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/indexer.py", line 155, in process_ckan
    self._process_ckan()
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/indexer.py", line 140, in _process_ckan
    if not self.Success and status.last_error != attrs.last_error:
AttributeError: 'dict' object has no attribute 'last_error'
```

**Comment by HebaruSan** [comment]
Someday I will figure out how people manage to be productive in this language.

**Comment by HebaruSan** [comment]
Maybe we could settle for making some of our objects less "Pythonic" by ensuring that their mission critical properties are always present?

**Comment by techman83** [comment]
Well we could do something with the `__getattr__` and we already have our own status class. Something to think about, but a little beyond a bugfix.

**Comment by HebaruSan** [comment]
I'm thinking more like unconditional assignments in `__init__`.

**Comment by techman83** [comment]
That's likely not going to work all that well with the PynamoDB stuff.
